### ISSUE TITLE
Update the wikis monitored by bots

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia/countervandalism-cvn-infrastructure#25]
I've run https://cvn.wmflabs.org/megatable/ with the list from [here](https://meta.wikimedia.org/wiki/Small_Wiki_Monitoring_Team/Groups) and there are a lot of wikis monitored more than once by different bots and also a lot of "non-swmt" wikis and closed wikis that might have to be removed. Also, there are missing newly created projects. Can someone from the CVN staff update this? Thanks!

**Comment by Krinkle** [comment]
I've synced the Meta-Wiki pages again and run the MegaTable.

Current results:

##### Wikis that no longer need to be monitored (locked, private/fishbowl, or too large)

- CVNBot7
-- be-x-old.wikipedia (unknown)
- CVNBot8
-- ru.wiktionary (large)
- CVNBot9
-- species.wikimedia (large)
- CVNBot19
-- et.wikimedia (unknown)
-- outreach.wikimedia (unknown)

#### Not yet monitored
- atj.wikipedia
- azb.wikipedia
- ba.wikibooks
- be-tarask.wikipedia
- bn.wikivoyage
- co.wiktionary
- da.wikipedia
- de.wikivoyage
- el.wikipedia
- el.wikivoyage
- eml.wikipedia
- en.wikivoyage
- es.wikivoyage
- fr.wikivoyage
- fur.wikipedia
- gom.wikipedia
- he.wikivoyage
- hi.wikisource
- hi.wikiversity
- hi.wikivoyage
- hif.wiktionary
- hyw.wikipedia
- it.wiktionary
- it.wikibooks
- it.wikinews
- it.wikiquote
- it.wikisource
- it.wikiversity
- it.wikivoyage
- ja.wiktionary
- ja.wikibooks
- ja.wikinews
- ja.wikiquote
- ja.wikisource
- ja.wikiversity
- kbp.wikipedia
- li.wikinews
- lij.wikipedia
- lrc.wikipedia
- mk.wikipedia
- mr.wikipedia
- nap.wikipedia
- nap.wikisource
- nl.wikinews
- nl.wikivoyage
- nn.wikipedia
- nqo.wikipedia
- pms.wikipedia
- pms.wikisource
- ps.wikivoyage
- ro.wikivoyage
- roa-tara.wikipedia
- ru.wikivoyage
- sah.wikiquote
- sat.wikipedia
- sc.wikipedia
- scn.wikipedia
- scn.wiktionary
- shn.wikipedia
- simple.wikipedia
- simple.wiktionary
- sv.wikivoyage
- uk.wikivoyage
- vec.wikipedia
- vec.wikisource
- vi.wikivoyage
- yue.wiktionary
- zh.wikiversity
- zh.wikivoyage
- ee.wikimedia
- wikitech.wikimedia
- labtestwikitech.wikimedia
- login.wikipedia
- pt.wikimedia
- test.wikipedia
- test2.wikipedia
- test-commons.wikimedia
- testwikidata.wikipedia

**Comment by Krinkle** [comment]
Log of changes:
```
CVNBot7 drop be-x-old.wikipedia
CVNBot7 load be-tarask.wikipedia

CVNBot19 drop outreach.wikimedia
CVNBot19 load outreach.wikipedia outreach:

CVNBot19 drop et.wikimedia
CVNBot19 load ee.wikimedia ee:chapter:

CVNBot7 drop species.wikipedia
CVNBot9 drop species.wikimedia
CVNBot9 load species.wikimedia species:
```
